testsuite/src/test/java/org/ironjacamar/common/metadata/resourceadapter/ResourceAdapters10TestCase.java
testsuite/src/test/java/org/ironjacamar/common/metadata/resourceadapter/ResourceAdapters11TestCase.java
testsuite/src/test/java/org/ironjacamar/common/metadata/resourceadapter/ResourceAdapters12TestCase.java
testsuite/src/test/resources/resourceadapter/dashra-1.0.xml
testsuite/src/test/resources/resourceadapter/dashra-1.1.xml
testsuite/src/test/resources/resourceadapter/dashra-1.2.xml

Resource adapters test case update

---

testsuite/src/test/java/org/ironjacamar/common/metadata/spec/JCA10TestCase.java
testsuite/src/test/java/org/ironjacamar/common/metadata/spec/JCA15TestCase.java
testsuite/src/test/java/org/ironjacamar/common/metadata/spec/JCA16TestCase.java
testsuite/src/test/java/org/ironjacamar/common/metadata/spec/JCA17TestCase.java
testsuite/src/test/resources/spec/ra-1.7.xml

JCA 1.5, 1.6, 1.7 parsers tests updated

JCA 1.5 test update

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Added parallel build execution and default file encoding too

Gradle 2.3

---

core/src/main/java/org/jboss/jca/core/workmanager/transport/remote/jgroups/JGroupsTransport.java

I'm not sure where to find the corresponding logic in master.

Generalize JGroupsTransport to use Channel, rather than JChannel.

---

.gitignore
api/build.gradle
build.gradle
common/build.gradle
core/build.gradle
testsuite/build.gradle

Distribution enablement

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/local/LocalManagedConnectionFactory.java
adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DataSourceTestCase.java
adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DriverDataSourceTestCase.java
adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DriverTestCase.java
adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DynamicDriverTestCase.java
adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2ModuleTestCase.java

Jira: https://issues.jboss.org/browse/JBJCA-1258
1. Removed driverCache from LocalManagedConnectionFactory
2. Removed interaction with DriverManager
3. Removed some unused imports and private methods

[JBJCA-1258] Remove driver cache and the interaction with DriverManager

---

core/src/main/java/org/jboss/jca/core/connectionmanager/pool/AbstractPool.java

JIRA: https://issues.jboss.org/browse/JBJCA-1276
BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1231658

[JBJCA-1276] Prefill race condition in flush

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java

Porting JBJCA-1297 to 1.0 branch
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1271806
JIRA: https://issues.jboss.org/browse/JBJCA-1297

[BZ-1271806] Verify if a SQLException is fatal in all methods

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java

[BZ-1271806] Fixing isolation level propagation 

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/local/LocalManagedConnectionFactory.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnectionFactory.java

A https://github.com/ironjacamar/ironjacamar/pull/434 backport for 1.2 branch.
Full description here:
https://issues.jboss.org/browse/JBJCA-1304

JBJCA-1304 invoke Subject.doAs() within doPrivileged block

---

core/src/main/java/org/jboss/jca/core/workmanager/WorkManagerImpl.java
core/src/test/java/org/jboss/jca/core/workmanager/unit/WorkManagerGracefulShutdownTestCase.java

https://bugzilla.redhat.com/show_bug.cgi?id=1280390

[BZ-1280390] JBoss WorkManager does not call WorkListener.workRejected at shutdown

---

adapters/src/main/java/org/jboss/jca/adapters/AdaptersBundle.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/local/LocalManagedConnectionFactory.java
adapters/src/test/resources/h2-driver-datasource-ds.xml

Jira: https://issues.jboss.org/browse/JBJCA-1312

[JBJCA-1312] connection-url is required when dataSourceClass is provided

---

core/src/main/java/org/ironjacamar/core/api/deploymentrepository/DeploymentRepository.java
core/src/main/java/org/ironjacamar/core/api/deploymentrepository/MessageListener.java
core/src/main/java/org/ironjacamar/core/api/deploymentrepository/ResourceAdapter.java
core/src/main/java/org/ironjacamar/core/deploymentrepository/ActivationSpecImpl.java
core/src/main/java/org/ironjacamar/core/deploymentrepository/DeploymentRepositoryImpl.java
core/src/main/java/org/ironjacamar/core/deploymentrepository/MessageListenerImpl.java
core/src/main/java/org/ironjacamar/core/deploymentrepository/ResourceAdapterImpl.java
deployers/src/main/java/org/ironjacamar/deployers/common/AbstractResourceAdapterDeployer.java
testsuite/src/test/java/org/ironjacamar/core/inflow/InflowTestCase.java
testsuite/src/test/java/org/ironjacamar/core/inflow/package-info.java
testsuite/src/test/java/org/ironjacamar/rars/ResourceAdapterFactory.java
testsuite/src/test/java/org/ironjacamar/rars/test/inflow/TestActivation.java

The new inflow architecture, activated/deactivated through the deployment repository.
InflowTestCase provides an overview of the usage

[#472] Inflow architecture

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/novendor/ListExceptionSorter.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/novendor/ListStaleConnectionChecker.java
doc/userguide/en-US/modules/deployment.xml

https://bugzilla.redhat.com/show_bug.cgi?id=1320720
cherry-pick https://github.com/ironjacamar/ironjacamar/pull/489 to 1.0 branch for EAP 6.4.x

JBJCA-1318: list driven ExceptionSorter, StaleConnectionChecker

---

core/src/main/java/org/jboss/jca/core/connectionmanager/listener/TxConnectionListener.java

https://issues.jboss.org/browse/JBJCA-1325

JBJCA-1325 fixing the condition with doSetRollbackOnly boolean

---

core/src/main/java/org/ironjacamar/core/workmanager/WorkWrapper.java
doc/src/main/asciidoc/developer-guide/chapters/_issuetracking.adoc
doc/src/main/asciidoc/developer-guide/chapters/_preface.adoc
doc/src/main/asciidoc/developer-guide/chapters/_releases.adoc
doc/src/main/asciidoc/developer-guide/chapters/_standalone.adoc
doc/src/main/asciidoc/developer-guide/chapters/_testing.adoc

Let me know if there is need to create an issue for this commit.

Small fixes for the developer guide.

---

deployers/src/main/java/org/jboss/jca/deployers/common/AbstractDsDeployer.java

Jira: https://issues.jboss.org/browse/JBJCA-1334

[JBJCA-1334] Add DataSource to ManagementRepository only after deployed successfully

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/db2/DB2ExceptionSorter.java

Issue: https://issues.jboss.org/browse/JBJCA-1341

[JBJCA-1341] Account for additional DB2 FATAL connection errors

---

common/src/main/java/org/jboss/jca/common/api/metadata/resourceadapter/AdminObject.java
core/src/main/java/org/jboss/jca/core/connectionmanager/AbstractConnectionManager.java

Jira: https://issues.jboss.org/browse/JBJCA-1352

[JBJCA-1352] Fix potential deadlock on shutdown

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnection.java
core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java

Jiras: 
https://jira.jboss.com/browse/JBJCA-1356
https://jira.jboss.com/browse/JBJCA-1368
https://jira.jboss.com/browse/JBJCA-1369

[JBJCA-1356][JBJCA-1368][JBJCA-1369] Fix bugs uncovered when JDBC connection times out

---

adapters/src/main/java/org/jboss/jca/adapters/AdaptersBundle.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnection.java
core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java

Jiras:
https://issues.jboss.org/browse/JBJCA-1367
https://issues.jboss.org/browse/JBJCA-1368
https://issues.jboss.org/browse/JBJCA-1369
https://issues.jboss.org/browse/JBJCA-1356
Porting fixes from 1.4. Some fixes required adaptation of code.
Please, disregard this PR if IJ 1.2 is no longer used and updated version.

[JBJCA-1367][JBJCA-1368][JBJCA-1369][JBJCA-1356] Fix bugs that are uncovered when a JDBC connection times out

---

core/src/main/java/org/jboss/jca/core/connectionmanager/ccm/CachedConnectionManagerImpl.java

Issue: https://issues.jboss.org/browse/JBJCA-1358

[JBJCA-1358] - Container is not cleaning up container-managed JMSContext

---

core/src/main/java/org/jboss/jca/core/api/connectionmanager/pool/PoolConfiguration.java

[JBJCA-1370]  Make PoolConfiguration.isPrefill return false when initialSize is 0

---

core/src/main/java/org/jboss/jca/core/api/connectionmanager/pool/PoolConfiguration.java

[JBJCA-1370] Make PoolConfiguration.isPrefill return false when initialSize is 0

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnectionFactory.java

Jira:
https://issues.jboss.org/browse/JBJCA-1371

[JBJCA-1371] Replace XAManagedConnectionFactory synchronized map xaProps by an unmodifiable version

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnectionFactory.java

[JBCA-1371] Replace XAManagedConnectionFactory synchronized map xaProps by an unmodifiable version

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/mysql/MySQLReplicationValidConnectionChecker.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/mysql/MySQLValidConnectionChecker.java

Jira: https://issues.jboss.org/browse/JBJCA-1373
Similar problem was with the replication checker.

[JBJCA-1373] MySQLValidConnectionChecker swallow a root cause of the exception

---

core/src/main/java/org/ironjacamar/core/connectionmanager/pool/PoolStatisticsImpl.java

https://issues.jboss.org/browse/JBJCA-1375
https://issues.jboss.org/browse/JBEAP-14635
Upstream PR for https://github.com/ironjacamar/ironjacamar/pull/665

JBJCA-1375 ActiveCount of data-source is not correct after reload

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnectionFactory.java

Fix of compilation error caused by commit:  7471c7038d10f94c65af6e74eb9e7c53b3d2fa90

Jbjca 1371 compilation fix for previous commit

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnectionFactory.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/SecurityActions.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnectionFactory.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrapperDataSource.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/jdk7/WrappedConnectionFactoryJDK7.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/jdk7/WrappedConnectionJDK7.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/jdk8/WrappedConnectionFactoryJDK8.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/jdk8/WrappedConnectionJDK8.java

JIRA: https://issues.jboss.org/browse/WFLY-10798, https://issues.jboss.org/browse/JBJCA-1386

[JBJCA-1386] adding TCCL in Wrapper*

---

core/src/main/java/org/jboss/jca/core/rar/EndpointImpl.java

Jira: https://issues.jboss.org/browse/JBJCA-1388

[JBJCA-1388] Validator is created using rar ClassLoader as the TCCL

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java
adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/WrapperTestCase.java

https://issues.jboss.org/browse/JBJCA-1389
https://issues.jboss.org/browse/JBEAP-16825

JBJCA-1389 NPE when isWrapperFor(...) called on closed connection

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java

https://issues.jboss.org/browse/JBJCA-1391

JBJCA-1391 except of null return original exception at least

---

core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java
core/src/test/java/org/jboss/jca/core/connectionmanager/pool/OnePoolNoTxDeploymentBlockingCountTestCase.java
core/src/test/java/org/jboss/jca/core/connectionmanager/pool/PoolTestCaseAbstract.java

https://issues.jboss.org/browse/JBJCA-1390

[JBJCA-1390] increase blocking count stats in case of IJ000655 error

---

core/src/main/java/org/jboss/jca/core/connectionmanager/listener/TxConnectionListener.java

[JBJCA-1393] Fixes #690 : Unguarded Transaction#toString() in trace message

---

build.xml

https://issues.jboss.org/browse/JBJCA-1395

[JBJCA-1395] Use HTTPS for JBoss repository during build now.

---

common/src/main/resources/schema/datasources_1_4_1.xsd

Changing the license of datasources schema

Chaning datasources_1.4.xsd licensing to EPL-1.0

---

core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java
core/src/test/java/org/jboss/jca/core/connectionmanager/unit/pool/mcp/SemaphoreArrayListManagedConnectionPoolTestCase.java
core/src/test/java/org/jboss/jca/core/connectionmanager/unit/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPoolTestCase.java

Jira: https://issues.redhat.com/browse/JBJCA-1404

[JBJCA-1404] Fix problem with connection pool size in SemaphoreConcurrentLinkedDequeManagedConnectionPool

---

core/src/main/java/org/jboss/jca/core/connectionmanager/ccm/CachedConnectionManagerImpl.java

https://issues.redhat.com/browse/JBJCA-1418

[JBJCA-1418] return when cached connection manager works with empty conns

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/SecurityActions.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java

There are two Java SE releases supported in this PR. JSE8 and JSE9.
For JSE8 or lower caching the binding outcome for faster execution. This is useful because a call always results in NoSuchMethodError.
Benchmarking using this [ironjacama-bench](https://gitlab.com/whitingjr/ironjacama-bench) project reveals the improvements for JSE8 using a cached failure status avoids subsequent expensive call attempts.
Higher Score is better.
```
Benchmark                                   Mode  Cnt          Score        Error  Units
JSE8IJBench.methodHandleJDK8CachedFailure  thrpt   25  973385131.166 ± 121684.584  ops/s
JSE8IJBench.methodHandleJDK8IgnoreFailure  thrpt   25      71919.407 ±  33683.858  ops/s
JSE8IJBench.reflectiveJSE8IgnoreFailure    thrpt   25     534453.651 ±   3561.461  ops/s
```
We …

[JBJCA-1410] Replaced reflective calls with MethodHandle. Cached the binding outcome.

---

build.xml
codegenerator/src/main/resources/build.gradle.template
codegenerator/src/main/resources/build.ivy.xml.template
codegenerator/src/main/resources/pom.xml.template
doc/developerguide/en-US/modules/standalone.xml

https://issues.redhat.com/browse/JBJCA-1424
TL;DR jesperpedersen.github.com is no longer working, we need to use jesperpedersen.github.io

[JBJCA-1424] Fungal repo now at jesperpedersen.github.io/fungal/maven2

---

common/src/main/java/org/jboss/jca/common/CommonLogger.java
common/src/main/java/org/jboss/jca/common/metadata/ds/DsPoolImpl.java
common/src/main/java/org/jboss/jca/common/metadata/ds/DsXaPoolImpl.java

Issue: https://issues.redhat.com/browse/JBJCA-1423

[JBJCA-1423] Warn if multi-user pool has prefill enabled

---

core/src/main/java/org/jboss/jca/core/connectionmanager/pool/api/Semaphore.java

Issue: https://issues.redhat.com/browse/JBJCA-1422
JBEAP issue: https://issues.redhat.com/browse/JBEAP-21012
also Java text formatted.

[JBJCA-1422] MaxWaitCount will be counted one less than waiting requests

---

as/src/main/java/org/jboss/jca/as/rarinfo/Main.java
as/src/main/java/org/jboss/jca/as/upgrader/Main.java
codegenerator/src/main/java/org/jboss/jca/codegenerator/Utils.java
deployers/fungal/src/main/java/org/jboss/jca/deployers/fungal/external/RemoteUndeploy.java
embedded/impl/src/main/java/org/jboss/jca/embedded/EmbeddedJCA.java
validator/impl/src/main/java/org/jboss/jca/validator/Validation.java

Fixes https://issues.redhat.com/browse/JBJCA-1438

[JBJCA-1438] Use java.nio.file.Files for deletion and directory creation

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/util/Injection.java
as/src/main/java/org/jboss/jca/as/rarinfo/Main.java
core/impl/src/main/java/org/jboss/jca/core/rar/SimpleResourceAdapterRepository.java
core/impl/src/main/java/org/jboss/jca/core/util/Injection.java
deployers/common/src/main/java/org/jboss/jca/deployers/common/AbstractDsDeployer.java
embedded/arquillian/src/main/java/org/jboss/jca/arquillian/embedded/EmbeddedJCAEnricher.java

https://issues.redhat.com/browse/JBJCA-1436

JBJCA-1436 Replace usages of getParameterTypes().length with getParameterCount()

---

deployers/fungal/pom.xml
ee-9/source-transform/deployers/fungal/pom.xml
ee-9/source-transform/embedded/tests/pom.xml

https://issues.redhat.com/browse/JBJCA-1443

[JBJCA-1443] Duplicate dependencies in pom.xml files

---

ee-9/pom.xml

https://issues.redhat.com/browse/JBJCA-1454

JBJCA-1454 Upgrade jakarta.ejb-api from 4.0.0 to 4.0.1

---

ee-9/pom.xml

https://issues.redhat.com/browse/JBJCA-1455

JBJCA-1455 Upgrade jakarta.transaction-api from 2.0.0 to 2.0.1

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnectionFactory.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/CheckValidConnectionSQL.java
adapters/src/main/java/org/jboss/jca/adapters/jdbc/spi/ValidConnectionChecker.java
as/src/main/java/org/jboss/jca/as/converters/DataSource.java
as/src/main/java/org/jboss/jca/as/converters/LegacyDsParser.java
as/src/main/java/org/jboss/jca/as/converters/LegacyTxDataSourceImpl.java
as/src/main/java/org/jboss/jca/as/converters/LegacyXaDataSourceImp.java
as/src/main/java/org/jboss/jca/as/converters/LocalTxDataSource.java
as/src/main/java/org/jboss/jca/as/converters/NoTxDataSource.java
as/src/main/java/org/jboss/jca/as/converters/XaDataSource.java
common/api/src/main/java/org/jboss/jca/common/api/metadata/ds/TimeOut.java
common/impl/src/main/java/org/jboss/jca/common/metadata/ds/DsParser.java
common/impl/src/main/java/org/jboss/jca/common/metadata/ds/TimeOutImpl.java
common/impl/src/test/resources/ds/unit/complex-ds.xml
common/impl/src/test/resources/ds/wrong/validation-query-timeout-negative-ds.xml
doc/developerguide/en-US/modules/metadata.xml
doc/userguide/en-US/modules/deployment.xml

Issue: https://issues.redhat.com/browse/JBJCA-1402
This is an IronJacamar's part of https://issues.redhat.com/browse/WFLY-17180 , see 
https://github.com/istudens/wildfly/commits/JBJCA-1402 .

[JBJCA-1402] add new validation-query-timeout attribute to datasources

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java

Issue: https://issues.redhat.com/browse/JBJCA-1473

[JBJCA-1473] Make WrappedConnection obey jdoc contract

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrapperDataSource.java

- throw SQLTimeoutException where appropriate
- throw SQLTransactionRollbackException where appropriate
https://issues.redhat.com/browse/JBJCA-1474

[JBJCA-1474] Throw more specific SQL exceptions

---

core/tests/src/test/java/org/jboss/jca/core/connectionmanager/unit/pool/mcp/SemaphoreArrayListManagedConnectionPoolTestCase.java
core/tests/src/test/java/org/jboss/jca/core/connectionmanager/unit/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPoolTestCase.java

Please check out my test case for [JBEAP-25148](https://issues.redhat.com/browse/JBEAP-25148).

Add JBEAP-25148 test case

---

adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/PreparedStatementTestCase.java

https://issues.redhat.com/browse/JBJCA-1488

[JBJCA-1488] Adapters: fix PreparedStatementTestCase after h2 upgrade

---

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/ccm/CachedConnectionManagerImpl.java

ISSUE-805: Replace the "connections.size() != 0" with "!connections.isEmpty()" in CachedConnectionManagerImpl.java 

---

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java

https://issues.redhat.com/browse/JBJCA-1498
https://issues.redhat.com/browse/JBEAP-27222
Backport of: https://issues.redhat.com/browse/JBJCA-1462
Commit: https://github.com/ironjacamar/ironjacamar/commit/bab021a5ee2ce326ab66aab60627292b8c33e9d2

[JBJCA-1498][JBEAP-27222] Backport of JBJCA-1462 - NullPointerException in ConnectionValidator

---

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java

https://issues.redhat.com/browse/JBJCA-1507
https://issues.redhat.com/browse/JBEAP-28303
Upstream PR: https://github.com/ironjacamar/ironjacamar/pull/875

[JBJCA-1507][JBEAP-28303] ConnectionListenerWrapper NullPointerException in ConnectionValidator

---

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java

https://issues.redhat.com/browse/JBJCA-1507
https://issues.redhat.com/browse/JBEAP-28304

[JBJCA-1507][JBEAP-28304] ConnectionListenerWrapper NullPointerException in ConnectionValidator

---

deployers/fungal/pom.xml
embedded/arquillian/pom.xml
embedded/impl/pom.xml
pom.xml
sjc/pom.xml
validator/tests/pom.xml

https://issues.redhat.com/browse/JBJCA-1509

[JBJCA-1509] Upgrade fungal to 0.12.0.Final

---

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java

Issue: https://issues.redhat.com/browse/JBJCA-1362

JBJCA-1362 NPE from SemaphoreConcurrentLinkedDequeManagedConnectionPool.returnForFrequencyCheck

---

adapters/src/main/java/org/jboss/jca/adapters/jdbc/xa/XAManagedConnection.java

Issue: https://issues.redhat.com/browse/JBEAP-29909
Upstream: https://issues.redhat.com/browse/JBJCA-1484
Upstream PR: 4c871bae3512f7302c60d04ee9f55ecefaab9c37

[JBCA-1484] XAManagedConnection: fix argument type of broadcastConnectionError
