adapters/src/main/java/org/jboss/jca/adapters/jdbc/local/LocalManagedConnectionFactory.java, adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DataSourceTestCase.java, adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DriverDataSourceTestCase.java, adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DriverTestCase.java, adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2DynamicDriverTestCase.java, adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/H2ModuleTestCase.java
[BZ-1157649] Multiple JDBC drivers versions - wrong driver is used
Bugzilla reference: https://bugzilla.redhat.com/show_bug.cgi?id=1157649
PR in 1.2 branch: https://github.com/ironjacamar/ironjacamar/pull/316
Should we use the same Jira for this, or create a new one?
=> [JBJCA-1258] Remove driver cache

build.xml
Specify `-sourceclasspath ${build.dir}` in `additionalparam` attribute to indicate apiviz to generate package dependency diagram.
Tested with and without `-Das`.
=> [Aggregated-javadocs] Generates package dependency diagrams

adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/oracle/OracleValidConnectionChecker.java
https://bugzilla.redhat.com/show_bug.cgi?id=1230981
Since we handled SQLException in EAP 5.2 and future IJ 1.2 series
1.0 branch backport of partial upstream commit https://github.com/ironjacamar/ironjacamar/commit/8dcbab49cead26a8113371ef48c075bc16adb17b#diff-9f8b3b8570171393f37acc1c02391c28R72 from 1.2 branch
=> BZ1230980 throw SQLException instead of log a warn message.

core/src/main/java/org/jboss/jca/core/workmanager/transport/remote/jgroups/JGroupsTransport.java
https://issues.jboss.org/browse/JBJCA-1289
Needed for https://issues.jboss.org/browse/WFLY-5188
Since the response marshaller really ought to be configured before the channel is connected, I opted for a separate factory method (which can be overridden) rather than merely exposing the RpcDispatcher field as protected.
Also, this PR applies to the 1.2 branch.  I don't see this class in master.
=> JBJCA-1289 Move RpcDispatcher creation to protected method to allow customization by subclasses.

rhq/src/test/java/org/jboss/jca/rhq/test/DsTestCase.java
There is no reason to shut the MCP down if there is only one MCP, so createdCount isn't cleared
=> [JBJCA-1276] fix DsTestCase

core/src/main/java/org/ironjacamar/core/api/deploymentrepository/AdminObject.java, core/src/main/java/org/ironjacamar/core/api/deploymentrepository/ConnectionFactory.java, core/src/main/java/org/ironjacamar/core/api/deploymentrepository/Deployment.java, core/src/main/java/org/ironjacamar/core/api/deploymentrepository/Recovery.java, core/src/main/java/org/ironjacamar/core/api/deploymentrepository/ResourceAdapter.java, core/src/main/java/org/ironjacamar/core/deploymentrepository/AdminObjectImpl.java, core/src/main/java/org/ironjacamar/core/deploymentrepository/ConnectionFactoryImpl.java, core/src/main/java/org/ironjacamar/core/deploymentrepository/DeploymentImpl.java, core/src/main/java/org/ironjacamar/core/deploymentrepository/RecoveryImpl.java, core/src/main/java/org/ironjacamar/core/deploymentrepository/ResourceAdapterImpl.java, core/src/main/java/org/ironjacamar/core/spi/transaction/TransactionIntegration.java, core/src/main/java/org/ironjacamar/core/tx/narayana/TransactionIntegrationImpl.java, core/src/main/java/org/ironjacamar/core/tx/narayana/XAResourceRecoveryImpl.java, core/src/main/java/org/ironjacamar/core/tx/noopts/TransactionIntegrationImpl.java, core/src/main/java/org/ironjacamar/core/tx/noopts/XAResourceRecoveryImpl.java, core/src/main/java/org/ironjacamar/core/tx/noopts/XAResourceRecoveryRegistryImpl.java, deployers/src/main/java/org/ironjacamar/deployers/common/AbstractResourceAdapterDeployer.java, embedded/src/main/resources/noop-transaction.xml, testsuite/src/test/java/org/ironjacamar/core/connectionmanager/pool/dflt/RecoveryTestCase.java, testsuite/src/test/java/org/ironjacamar/rars/ResourceAdapterFactory.java, testsuite/src/test/java/org/ironjacamar/rars/txlog/TxLogConnection.java, testsuite/src/test/java/org/ironjacamar/rars/txlog/TxLogConnectionImpl.java, testsuite/src/test/java/org/ironjacamar/rars/txlog/TxLogManagedConnection.java, testsuite/src/test/java/org/ironjacamar/rars/txlog/TxLogManagedConnectionFactory.java
This pull requests adds support for outbound recovery.
NoopTS has been changed to trigger a single recovery pass of the associated XAResource instances during startup.
Furthermore the signature of the deployment repository components has been changed for activate and deactivate in order to provide feedback to the caller on the result of the operation. This will help in making lifecycle changes easier. F.ex. recovery can be activated and deactivated in a cycle now at run-time.
=> [#467] Recovery (outbound)

core/src/main/java/org/jboss/jca/core/CoreLogger.java, core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreArrayListManagedConnectionPool.java, core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java
This is cherry-picked from PR: https://github.com/ironjacamar/ironjacamar/pull/475, with some conflicts.
Jira: https://issues.jboss.org/browse/JBJCA-1314
=> [JBEAP-2995] Log datasource name in warn message when Network Adapter fails to establish connection with database.

core/src/main/java/org/jboss/jca/core/CoreLogger.java, core/src/main/java/org/jboss/jca/core/connectionmanager/pool/strategy/PoolBySubject.java, deployers/src/main/java/org/jboss/jca/deployers/common/AbstractDsDeployer.java
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1315439
Added jndi-name in the console log
=> [BZ:1315439] [GSS] (6.4.z) Difficult to identify datasource with wrong credentials if security-domain is used.

core/src/main/java/org/jboss/jca/core/CoreLogger.java, core/src/main/java/org/jboss/jca/core/connectionmanager/pool/strategy/PoolBySubject.java, deployers/src/main/java/org/jboss/jca/deployers/common/AbstractDsDeployer.java
Jira: https://issues.jboss.org/browse/JBJCA-1317
=> [JBJCA-1317] Log jndi-name in console log to identify datasource with wrong credentials if security-domain is used

adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedStatement.java, adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/PreparedStatementTestCase.java
Jira: https://issues.jboss.org/browse/JBJCA-1321
Remove the lock from `WrappedStatement.cancel()`
=> [JBJCA-1321] Statement.cancel() is not invoked until the statement is completed

adapters/src/main/java/org/jboss/jca/adapters/jdbc/local/LocalManagedConnectionFactory.java, deployers/src/main/java/org/jboss/jca/deployers/DeployersLogger.java, deployers/src/main/java/org/jboss/jca/deployers/common/AbstractDsDeployer.java
Jira: https://issues.jboss.org/browse/JBJCA-1331
Try to use `driver-class` & `connection-url` to connect database if the `connection-properties` is empty and `data-source-class` is defined with a warning message in log.
=> [JBJCA-1331] Use connection-url to get database connection when connection properties for datasource-class is empty

adapters/src/test/java/org/jboss/jca/adapters/jdbc/unit/PreparedStatementTestCase.java
improvement for test for https://issues.jboss.org/browse/JBJCA-1321
The test will now also check that we didn't really have to wait until the statement was complete.
=> JBJCA-1321 test improvement

adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/db2/DB2ExceptionSorter.java
Issue: https://issues.jboss.org/browse/JBJCA-1341
I refactored the code a bit to make it less prone to issues.
=> [JBJCA-1341] Account for additional DB2 FATAL connection errors

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnectionFactory.java
...preventing application from changing transaction isolation level (PostgreSQL)
https://issues.jboss.org/browse/JBJCA-1338
https://issues.jboss.org/browse/WFLY-8032
https://issues.jboss.org/browse/JBEAP-8694
Second try...
=> JBJCA-1338 CheckValidConnectionSQL can open a transaction

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java
Backporting from 1.4.
https://bugzilla.redhat.com/show_bug.cgi?id=1195079
Upstream Issue: https://issues.jboss.org/browse/JBEAP-8789
Upstream PR: https://github.com/ironjacamar/ironjacamar/pull/627
=> bz-1195079 CheckValidConnectionSQL can open a transaction

build.xml, core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java
In flush(), parallelize the destruction of every
ConnectionListenerWrapper instead of doing them sequentially so that the
total time to flush the pool is reduced.
JIRA: https://issues.jboss.org/browse/JBJCA-1353
=> [JBJCA-1353] Parallelize destruction of managed connections

build.xml, core/.classpath, core/src/main/java/org/jboss/jca/core/connectionmanager/tx/TxConnectionManagerImpl.java, ivy.xml
https://issues.jboss.org/browse/JBJCA-1378
https://issues.jboss.org/browse/JBEAP-13301
According to https://github.com/wildfly/wildfly-transaction-client/pull/38 datasource implementation should be able to use wildfly-transaction-client API to determine remaining transaction timeout, hence I'm adding new dependency.
=> JBJCA-1378 Use new API to determine remaining transaction timeout

build.xml
Jira: https://issues.jboss.org/browse/JBJCA-1383
Move scope of `ironjacamar-spec-api` from `runtime` to `provided`.
=> [JBJCA-1383] Dependency of ironjacamar-spec-api should be in provided scope

adapters/build.xml, api/build.xml, build.xml, codegenerator/build.xml, common/build.xml, core/build.xml, deployers/build.xml, embedded/build.xml, rhq/build.xml, sjc/build.xml, validator/build.xml, web/build.xml
Add javac.encoding=UTF-8  to avoid compile error on platform where the default encoding is different from UTF-8
Signed-off-by: Francis ANDRE <francis.andre.kampbell@orange.fr>
=> Add javac.encoding=UTF-8 to javac

adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrapperDataSource.java
https://issues.jboss.org/browse/JBJCA-1394
https://issues.jboss.org/browse/WFLY-12676 
https://issues.jboss.org/browse/WFLY-12671 (original leak issue reported against WF17, not clear if its the same cause yet or an actual leak yet).
=> JBJCA-1394 clear (TCCL) mcf classloader reference in getConnection()

build.xml
Maven central moved to HTTPS and returns HTTP 501 on HTTP requests.
https://blog.sonatype.com/central-repository-moving-to-https
IronJacamar build then fails with errors like:
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/apache/ant/ant/1.8.1/ant-1.8.1.jar
=> use https for maven central

core/src/test/java/org/jboss/jca/core/connectionmanager/unit/pool/mcp/SemaphoreArrayListManagedConnectionPoolTestCase.java
This is a followup for previous JBJCA-1404 commits https://github.com/ironjacamar/ironjacamar/pull/701
That PR added new testcase similar to the SemaphoreConcurrentLinkedDequeManagedConnectionPoolTestCase but missed the addition of the workaround for `testFillTo()`
We need the same workaround also for SemaphoreArrayListManagedConnectionPoolTestCase to prevent intermittent race conditions during testing.
After this patch these tests are alike:
SemaphoreConcurrentLinkedDequeManagedConnectionPoolTestCase#testFillTo()
SemaphoreArrayListManagedConnectionPoolTestCase#testFillTo()
=> [JBJCA-1404] Prevent pool filler thread to run parallel with test

adapters/src/main/java/org/jboss/jca/adapters/jdbc/SecurityActions.java, adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java
This PR looks to fix some typos introduced in #716. Plus reinstate the use of Optional.
The performance results for JSE8 in this 2nd round are as follows.
```
Benchmark                      Mode  Cnt          Score         Error  Units
JSE8IJBench.methodHandleJDK8  thrpt    5  971785165.970 ± 3814383.265  ops/s
JSE8IJBench.reflectiveJSE8    thrpt    5  972288859.880 ± 4648031.680  ops/s
```
These results show both MethodHandle and Reflective to be the same as expected.
For JSE9 these are the results
```
Benchmark                      Mode  Cnt          Score        Error  Units
JSE9IJBench.methodHandleJSE9  thrpt   25  157610604.062 ± 173456.549  ops/s
JSE9IJBench.reflectiveJSE9    thrpt   25  123311938.959 ± 599554.129  ops/s
```
This shows an improvement using MethodHandle.
=> Corrected use of MethodHandle to invoke method. Uses Optional.

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java, adapters/src/main/java/org/jboss/jca/adapters/jdbc/SecurityActions.java, adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedConnection.java
The current lifecycle of the cached references is associated with the WrappedConnection. This lifecycle is "single use" disposable instance for j.s.Connection users (application code).
Instead the lifecycle should be associated with the ManagedConnection instance.
This PR makes the necessary changes to ensure the lifecycle of method references remain reachable (caching it). Ensuring the subsequent use of a ManagedConnection can find the cached MethodHandle as originally intended.
This has been tested to work as expected on JDK8 and JDK9.
=> [JBJCA-1410] Fix reference caching to match the lifecycle of a ManagedConnection.

codegenerator/src/main/resources/build.gradle.template, codegenerator/src/main/resources/build.ivy.xml.template, codegenerator/src/main/resources/pom.xml.template, doc/src/main/asciidoc/developer-guide/chapters/_standalone.adoc
https://issues.redhat.com/browse/JBJCA-1424
TL;DR jesperpedersen.github.com is no longer working, we need to use jesperpedersen.github.io
port of https://github.com/ironjacamar/ironjacamar/pull/721
@tadamski the changes are trivial, I was, however, unable to verify as the current branch seems unbuildable
=> [JBJCA-1424] Fungal repo now at jesperpedersen.github.io/fungal/maven2

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnectionFactory.java
Issue: https://issues.redhat.com/browse/JBJCA-1427
EAP Issue: https://issues.redhat.com/browse/JBEAP-22286
When `DataSource.getConnection(username, password)` is called, it should use username/password specified in the method call instead of using kerberos username.
=> [JBJCA-1427] user and password should be copied to the properties if they are specified

codegenerator/src/main/resources/build.ivy.xml.template, codegenerator/src/main/resources/build.xml.template, doc/developerguide/en-US/modules/building.xml
Based on RadHat JDK 17 effort, it was suggested to get rid of -XX:MaxPermSize=256m jvm arguments, because it's useless since JDK8.
=> Remove MaxPermSize jvm options

adapters/src/main/java/org/jboss/jca/adapters/jdbc/extensions/mysql/MySQLReauthPlugin.java
There is a typo in exception message, making debuging harder. This MR fixes it.
=> Fix typo in exception message

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/ManagedConnectionPoolFactory.java, core/impl/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java, doc/developerguide/en-US/modules/pool.xml, tools/findbugs/filter.xml
Issue: https://issues.redhat.com/browse/JBJCA-1470
=> [JBJCA-1470] typo at toString method in SemaphoreConcurrentLinkedDequeManagedConnectionPool class

pom.xml
Bumping the library to avoid [CVE-2022-0853](https://devhub.checkmarx.com/cve-details/CVE-2022-0853/)
=> [JBJCA-1485] Bump wildfly-transaction-client to 3.0.3.Final

adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnection.java, adapters/src/main/java/org/jboss/jca/adapters/jdbc/BaseWrapperManagedConnectionFactory.java, adapters/src/main/java/org/jboss/jca/adapters/jdbc/local/LocalManagedConnectionFactory.java
Before change, I ran:
spotbugs-4.8.3/bin/spotbugs -textui -project /home/smarlow/tools/spotbugs-4.8.3/ironjacamar.xml  &> spotbugsoutput2.txt
After change, I ran:
spotbugs-4.8.3/bin/spotbugs -textui -project /home/smarlow/tools/spotbugs-4.8.3/ironjacamar.xml  &> spotbugsoutput3.txt
Output of `grep "M M IS: Inconsistent synchronization" spotbugsoutput2.txt| grep org.jboss.jca.adapters.jdbc` shows:
> grep "M M IS: Inconsistent synchronization" spotbugsoutput2.txt| grep org.jboss.jca.adapters.jdbc
> M M IS: Inconsistent synchronization of org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnectionFactory.connectionListenerClassName; locked 55% of time  Unsynchronized access at BaseWrapperManagedConnectionFactory.java:[line 861]
> M M IS: Inconsistent synchronization of …
=> eliminate spotbugs Inconsistent synchronization in org.jboss.jca.adapters.jdbc classes

pom.xml
It gets rid of the CVE-2020-15250 warning
=> Bump to JUnit 4.13.2

core/impl/src/main/java/org/jboss/jca/core/connectionmanager/listener/AbstractConnectionListener.java
ISSUE: https://issues.redhat.com/browse/JBJCA-1500
=> [JBJCA-1500] AbstractConnectionListener#isTimedOut can return false for timed out connections

.github/workflows/ci.yml
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
otherwise GH CI fails like in https://github.com/ironjacamar/ironjacamar/pull/906
=> Upgrade actions/cache to v4

core/tests/src/test/java/org/jboss/jca/core/workmanager/spec/chapter10/api/WorkManagerStartWorkTestCase.java
https://issues.redhat.com/browse/JBJCA-1493
reverts changes from https://github.com/ironjacamar/ironjacamar/commit/eee47585dc0d2c58dc9124ad4b750f3393f6a81d#diff-3ef3abd32ff8585ea77554478f5974550b24ed2f6e21586db60d2399d7676ea8R192
=> [JBJCA-1493] fix postRun check in WorkManagerStartWorkTestCase#testStartWorkFullSpecWithImmediateStartTimeout
